export const PRODUCT = {
  productModel: {
    isVisible: true,
    visibility: true,
    isSetPublishDate: false,
    onlyHideFromList: false,
    publishDate: "2025-01-23T04:29:52.559Z",
    visibilityPOS: true,
    defaultVariant: {
      isChargeTaxes: true,
      isTrackingInventory: true,
      isShipping: true,
      price: 30000000,
      weight: 0,
      quantity: 0,
      option1: "Title",
      value1: "Default Title",
      defaultVariantType: "Title",
      isDefaultVariant: true,
      allowPurchaseWhenSoldOut: false,
      isGetDefaultVariantProperies: true,
      productOptionValues: [
        {
          optionName: "Title",
          optionValue: "Default Title",
          versionNo: null,
          isCustom: false,
          isDeleted: false,
        },
      ],
      taxable: false,
      taxRate: 0,
      isDefaultTax: false,
      inventories: [
        {
          locId: 3358861,
          name: "kho Bình dương",
          quantity: 1000,
          isPrimaryLocation: true,
        },
      ],
      oldPrice: 29000000,
      maCostAmount: 25000000,
    },
    productChannelList: [
      {
        channelId: 16,
        channelName: "Harasocial",
        channelCode: "harasocial",
        selectedCategoryId: 0,
        isConnect: true,
        categoryList: [],
        brandNames: null,
        selectedBrandName: null,
        isHasCategory: false,
        inventoryTypes: null,
        selectedInventoryType: null,
        linkToViewProduct: null,
        categoryName: null,
        isNewChannel: false,
        channelStatus: 0,
        branchIds: null,
      },
    ],
    productName: "Xe máy",
    productVendorName: "Vinfash",
    productTypeName: "Xe máy điện",
    descriptions: "mô tả&nbsp;",
    pageTitle: "Xe máy",
  },
  variantModel: [
    {
      productOptionValues: [
        {
          optionName: "Size",
          isCustom: false,
          optionValue: "XL",
        },
        {
          optionName: "Color",
          isCustom: false,
          optionValue: "Đỏ",
        },
      ],
      price: 30000000,
      oldPrice: 29000000,
      maCostAmount: 25000000,
      isCreated: true,
      weight: 0,
      isShipping: true,
      taxable: false,
      taxRate: 0,
      isDefaultTax: false,
      isTrackingInventory: true,
      lotSupport: false,
      inventories: [
        {
          locId: 3358861,
          name: "kho Bình dương",
          quantity: 1000,
          isPrimaryLocation: true,
        },
      ],
      id1: "22",
      option1: "Size",
      optionName1: "Kích thước",
      value1: "XL",
      customOption1: false,
      id2: "23",
      option2: "Color",
      optionName2: "Màu sắc",
      value2: "Đỏ",
      customOption2: false,
      sku: "",
      barcode: "",
      isChecked: false,
      quantity: 1000,
      allowPurchaseWhenSoldOut: false,
      variantUnits: [],
    },
  ],
  collectionModel: null,
  collectionIds: null,
};
