require("dotenv").config();

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL; // Ensure this is defined, e.g., "http://127.0.0.1:8084"

module.exports = {
    ilum: {
        output: {
            mode: "tags-split",
            target: "src/generated/index.ts",
            filters: {
                // Exclude endpoints with "healthcheck" in their tags
                tags: [/^(?!.*healthcheck).*$/],
            },
            schemas: "src/generated/model",
            client: "react-query",
            override: {
                header: () => [
                    "@ts-nocheck",
                    "Generated by orval 🍺",
                    "Do not edit manually.",
                ],
                mutator: {
                    path: "src/lib/api.ts",
                    name: "axiosMutator",
                },
                operationName: (operation: any) => {
                    // Remove any "Controller" text and convert to camelCase.
                    let opName = operation.operationId.replace(
                        /Controller/gi,
                        ""
                    );
                    const words = opName.split(/[_\s-]+/);
                    return words
                        .map((word: string, index: number) =>
                            index === 0
                                ? word.toLowerCase()
                                : word.charAt(0).toUpperCase() +
                                  word.slice(1).toLowerCase()
                        )
                        .join("");
                },
            },
        },
        input: {
            // Use the env variable to build the URL
            target: `${API_BASE_URL}/api/api-json`,
            // target: 'opeanapi.json',
        },
    },
};
