name: Deploy Admin App To Netlify

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./siteadmin
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Install dependencies and clear npm cache
              run: |
                  npm cache clean --force
                  npm install
                  npm install -g netlify-cli

            - name: Build
              run: npm run build

            - name: Deploy to Netlify
              run: netlify deploy --dir=build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
